name: todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_slidable: ^3.1.2
  flutter_spinkit: ^5.2.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.0
  permission_handler: ^11.3.1
  android_alarm_manager_plus: ^4.0.5
  just_audio: ^0.9.42
  android_intent_plus: ^5.2.1
  awesome_notifications: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/playtime.mp3
    - assets/app_icon.png
